title: chae0707
description: > # this means to ignore newlines until "baseurl:"
  hello
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://chae0707.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Jungmin Chae
tagline: student
about-description: # Add Discription
pic: 15.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below
# Contact links
email: chaejm77@gmail.com # Add your Email address
phone: 010 2051 2448 # Add your Phone number
website: chae0707.github.io # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: chae0707 # Add your Github handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
